security:
    encoders:
        App\User\Entity\User: bcrypt
    providers:
        users_by_username:
            entity:
                class: App\User\Entity\User
                property: username
        users_by_email:
            entity:
                class: App\User\Entity\User
                property: email
        users:
            chain:
                providers: [users_by_username, users_by_email]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: users
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
